version: "3"

services:
  server:
    build: Backend/
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_PORT=5432
      - POSTGRES_DB=postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:8080
  postgres:
    image: postgres:13.1
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - APP_DB_USER=postgres
      - APP_DB_PASS=postgres
      - APP_DB_NAME=postgres
    volumes:
      - ./DB/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
